#!/bin/sh

envFile=/home/node/app/client/.env

touch $envFile

cat << EOF > $envFile
PORT=$PORT
NODE_ENV=$NODE_ENV
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD=$ADMIN_USERNAME
SECRET_KEY=$SECRET_KEY
JWT_SECRET=$JWT_SECRET
JWT_EXPIRATION=$JWT_EXPIRATION
JWT_REFRESH_EXPIRATION=$JWT_REFRESH_EXPIRATION
ISSUER=$ISSUER
AUDIENCE=$AUDIENCE
GCP_MAP_API_KEY=$GCP_MAP_API_KEY
COSMOSDB_CON=$COSMOSDB_CON
DB_CONNECTION_CLUSTER=$DB_CONNECTION_CLUSTER
SCHEMA_DIR_PROD=$SCHEMA_DIR_PROD
IMAGES_UPLOAD_DIR_PROD=$IMAGES_UPLOAD_DIR_PROD
CORES_DMAINS_PROD=$CORES_DMAINS_PROD
STATIC_URL_PROD=$STATIC_URL_PROD
EOF
sleep 2

echo "printing the first two line from the .env file"
head -2 $envFile
#echo "moving env file to client directory"
#mv .env ./client
#echo  $envFile

npm run client