"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.uploadSchema = exports.uploadImages = exports.AccountRoutes = exports.ConfigRoutes = exports.DefaultRoutesConfig = exports.cors = exports.corsWithOptions = void 0;
const cors_config_js_1 = require("./lib/cors.config.js");
Object.defineProperty(exports, "cors", { enumerable: true, get: function () { return cors_config_js_1.cors; } });
Object.defineProperty(exports, "corsWithOptions", { enumerable: true, get: function () { return cors_config_js_1.corsWithOptions; } });
const account_routes_config_js_1 = require("./lib/account.routes.config.js");
Object.defineProperty(exports, "AccountRoutes", { enumerable: true, get: function () { return account_routes_config_js_1.AccountRoutes; } });
const default_routes_config_js_1 = require("./lib/default.routes.config.js");
Object.defineProperty(exports, "DefaultRoutesConfig", { enumerable: true, get: function () { return default_routes_config_js_1.DefaultRoutesConfig; } });
const config_routes_config_js_1 = require("./lib/config.routes.config.js");
Object.defineProperty(exports, "ConfigRoutes", { enumerable: true, get: function () { return config_routes_config_js_1.ConfigRoutes; } });
const uploads_js_1 = require("./lib/uploads.js");
Object.defineProperty(exports, "uploadImages", { enumerable: true, get: function () { return uploads_js_1.uploadImages; } });
Object.defineProperty(exports, "uploadSchema", { enumerable: true, get: function () { return uploads_js_1.uploadSchema; } });
